#' Convert a plaintext file into an ASCII file
#' 
#' This function reads a plaintext file and writes an ASCII art version to a new file.
#' It respects newlines and doesn't automatically wrap lines.
#'
#' @param size Character height, from `configure`
#' @param char_library Character library, from `load_files`
#' @param in_file Name of a plaintext file to read
#' @param out_file Name of a txt file to write the output to 
#'
#' @returns None. The output is written to `out_file`.
#' @export
#' 
#' @description
#' It respects newlines and doesn't automatically wrap.
#' 
#'
#' @examples
#' \dontrun{
#' settings <- asciiConverter::configure()
#' char_lib <- asciiConverter::load_files(settings$directory, settings$filenames)
#' file_to_file(
#'   size = settings$size,
#'   char_library = char_lib,
#'   in_file = "input.txt",
#'   out_file = "output_ascii.txt")
#' }
file_to_file <- function(size, char_library, in_file, out_file){
  if(missing(in_file) || !file.exists(in_file)){
    stop(paste("Input file does not exist:", in_file))
  }
  
  if(missing(out_file) || !is.character(out_file) || nchar(out_file) == 0){
    stop("You must provide a valid `out_file` name.")
  }

  if(missing(size) || !is.numeric(size) || size <= 0){
    stop("`size` must be a positive number.")
  }
  
  if(missing(char_library) || !is.list(char_library) || length(char_library) == 0){
    stop("`char_library` must be a non-empty list generated by `load_files()`.")
  }
  the_string <- scan(file = in_file, what = character(), sep = "\n")
  v <- map(the_string, asciiConverter::string_convert)
  for(x in 1:length(v)){
    asciiConverter::write_all_lines(v[[x]], size, char_library, out_file)
  }
}