#' Convert text from the R console
#'
#' @param size A double representing letter height; should match the value set by `configure()`.
#' @param char_library The character library generated by `load_files()`.
#'
#' @returns None. Output is printed directly to the console.
#' @export
#' @importFrom purrr map
#'
#' @examples
#' \dontrun{
#' a <- asciiConverter::configure()
#' b <- asciiConverter::load_files(a[[2]], a[[1]])
#' interactive_1(a[[4]], b)
#' # Type text and press Enter twice
#' }
interactive_1 <- function(size, char_library) {
  the_string <- scan(what = character(), quiet = TRUE)
  
  v <- map(the_string, asciiConverter::string_convert)
  
  for (x in seq_along(v)) {
    asciiConverter::make_lines(v[[x]], size, char_library)
  }
}

