#' Convert text from the R console
#'
#' @param size A double representing letter height, should match the value set by `configure`
#' @param char_library The library generated by `load_files`
#'
#' @returns None, output is printed to the console
#' @export
#' 
#' @importFrom purrr map
#'
#' @examples
#' a <- asciiConverter::configure()
#' b <- asciiConverter::load_files(a[[2]], a[[1]])
#' interactive(7, b, a[[4]])
#' #now type something and press enter twice
interactive_1 <- function(size, char_library){
  the_string <- scan(what = character())
  v <- map(the_string, asciiConverter::string_convert)
  for(x in 1:length(v)){
    asciiConverter::make_lines(v[[x]], size, char_library)
  }
}
