#' Add line breaks
#'
#' @param line Numeric or integer vector, preferably generated by `string_convert()`.
#' @param size Integer. Number of characters per line.
#'
#' @returns A list where each element is a vector of length `size`, the last element will be smaller
#' if the length of line is not a multiple of `size`
#' @export
#'
#' @examples
#' \dontrun{
#' x <- line_breaks(1:10, 4)
#' x
#' }
line_breaks <- function(line, size){
  new_lines <- split(line, ceiling(seq_along(line)/size))
  return(new_lines)
}