#' Add line breaks
#'
#' @param line Integer vector, preferable generated by `string_convert`
#' @param size The number of characters to print per line
#'
#' @returns A list where each element is a vector of length `size`, the last element will be smaller
#' if the length of line is not a multiple of `size`
#' @export
#'
#' @examples
#' x <- line_breaks(1:10, 4)
#' x
line_breaks <- function(line, size){
  new_lines <- split(line, ceiling(seq_along(line)/size))
}