#' Get letters into strings 
#'
#' @param indexes The indexes of the letters you want
#' @param size The length of your letter
#' @param char_library The list of vectors of letters
#' @param filename A txt file to write the output to
#' 
#' @description
#' Generates output text and writes it to a file
#' 
#' @details
#' Indexes should be generated by `string_convert()`, size can be taken from output
#' of `configure()`, and char_library should be generated by `load_files()`
#' 
#'
#' @returns A vector with length `size`, where element n a string of the concatenations of the nth line
#' of each file
#' @export
#'
#' @examples
#' \dontrun{
#' "here is where the examples would be if i wrote any"
#' }
make_file <- function(indexes, size, char_library, filename){
  for(y in 1:size){
    line_1 <- ""
    for(x in indexes){
      line_1 <- paste(line_1, char_library[[x]][y])
    }
    cat(line_1, "\n", file = filename)
  }
  
  
}