#' Get letters into strings 
#'
#' @param indexes Numeric vector. Indexes of letters to convert (from `string_convert()`).
#' @param size Integer. Height of each ASCII letter (from `configure()`).
#' @param char_library List. Character library created by `load_files()`.
#' @param filename Character. Path to the output file.
#' 
#' 
#' @returns A vector with length `size`, where element n a string of the concatenations of the nth line
#' of each file
#' @export
#' 
#' @description
#' Generates output text and writes it to a file
#' 
#' @details
#' Indexes should be generated by `string_convert()`, size can be taken from output
#' of `configure()`, and char_library should be generated by `load_files()`
#' 
#'
#'
#' @examples
#' \dontrun{
#' settings <- asciiConverter::configure()
#' char_lib <- asciiConverter::load_files(settings$directory, settings$filenames)
#' letters <- asciiConverter::string_convert("HELLO")
#' make_file(letters, settings$size, char_lib, "output.txt")
#' }
make_file <- function(indexes, size, char_library, filename){
  if(missing(indexes) || !is.numeric(indexes) || length(indexes) == 0){
    stop("`indexes` must be a non-empty numeric vector.")
  }

  if(missing(size) || !is.numeric(size) || size <= 0){
    stop("`size` must be a positive number.")
  }
  
  if(missing(char_library) || !is.list(char_library) || length(char_library) == 0){
    stop("`char_library` must be a non-empty list generated by `load_files()`.")
  }

  if(missing(filename) || !is.character(filename) || nchar(filename) == 0){
    stop("You must provide a valid `filename` to write the output.")
  }
  
  for(y in 1:size){
    line_1 <- ""
    for(x in indexes){
      line_1 <- paste(line_1, char_library[[x]][y])
    }
    cat(line_1, "\n", file = filename)
  }
}