#' Get letters into strings 
#'
#' @param indexes Numeric vector. Indexes of letters to convert (from `string_convert()`).
#' @param size Integer. Height of each ASCII letter (from `configure()`).
#' @param char_library List. Character library created by `load_files()`.
#' 
#' @returns A vector with length `size`, where element n a string of the concatenations of the nth line
#' of each file
#' @export
#' 
#' @description
#' This is the workhorse of the package, which actually generates the output text
#' 
#' @details
#' Indexes should be generated by `string_convert()`, size can be taken from output
#' of `configure()`, and char_library should be generated by `load_files()`
#' 
#'

#'
#' @examples
#' \dontrun{
#' settings <- asciiConverter::configure()
#' char_lib <- asciiConverter::load_files(settings$directory, settings$filenames)
#' letters <- asciiConverter::string_convert("HELLO")
#' make_lines(letters, settings$size, char_lib)
#' }
make_lines <- function(indexes, size, char_library){
  for(y in 1:size){
    line_1 <- ""
    for(x in indexes){
      line_1 <- paste(line_1, char_library[[x]][y])
    }
    cat(line_1, "\n")
  }
  
  
}