#' Convert text from the R console and save it to a file
#'
#' @param size A double representing letter height, should match the value set by `configure`
#' @param char_library The library generated by `load_files`
#' @param filename Name of a file, in double quotes (")
#'
#' @returns None, output is appended to the provided file
#' @export
#' 
#' @importFrom purrr map
#'
#' @examples
#' a <- asciiConverter::configure()
#' b <- asciiConverter::load_files(a[[2]], a[[1]])
#' type_to_file(7, b, a[[4]])
#' #now type something and press enter twice, then check the file
type_to_file <- function(size, char_library, filename){
  the_string <- scan(what = character())
  v <- map(the_string, asciiConverter::string_convert)
  for(x in 1:length(v)){
    asciiConverter::write_all_lines(v[[x]], size, char_library, filename)
  }
}