#' Write to a file
#'
#' @param indexes The indexes of the letters you want
#' @param size The length of your letter
#' @param char_library The list of vectors of letters
#' @param filename A blank txt file for storing the output
#' 
#' @description
#' Use this instead of make_lines for anything longer than 15 characters
#' 
#' @details
#' Indexes should be generated by `string_convert()`, size can be taken from output
#' of `configure()`, and char_library should be generated by `load_files()`
#' 
#'
#' @returns A vector with length `size`, where element n a string of the concatenations of the nth line
#' of each file
#' @export
#'
#' @examples
#' \dontrun{
#' settings <- asciiConverter::configure()
#' char_lib <- asciiConverter::load_files(settings$directory, settings$filenames)
#' letters <- asciiConverter::string_convert("HELLO WORLD")
#' write_all_lines(letters, settings$size, char_lib, "output_ascii.txt")
#' }
write_all_lines <- function(indexes, size, char_library, filename){
  con <- file(filename, open = "a")
  for(y in 1:size){
    line_1 <- ""
    for(x in indexes){
      line_1 <- paste(line_1, char_library[[x]][y])
    }
    cat(line_1, "\n", file = con)
  }
  close(con)
}